[lib]
crate-type = ["rlib"]

[package]
name = "uninit"
version = "0.2.0"
authors = ["Daniel Henry-Mantilla <daniel.henry.mantilla@gmail.com>"]
edition = "2018"

documentation = "https://docs.rs/uninit"
homepage = "https://crates.io/crates/uninit"

description = "A collection of tools for a safer usage of uninitialized memory"
keywords = ["uninit", "sound", "unsafe", "read", "MaybeUninit"]
categories = ["memory-management", "rust-patterns"]

readme = "README.md"
license = "MIT"

[dependencies]

[features]
std = []
nightly = []
specialization = ["nightly"]
const_generics = ["nightly"]
chain = []

default = ["std"]

[package.metadata.docs.rs]
all-features = true
rustc-args = ["-C", "opt-level=2"]
